"""akl

Revision ID: 0a7998f022c9
Revises: a2984adafbdf
Create Date: 2023-10-27 14:13:33.940938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7998f022c9'
down_revision = 'a2984adafbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electrotherapy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('recoveryairProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recoveryairProducts', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('electrotherapy', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
