"""addprice

Revision ID: 453fe0350c8d
Revises: de3dc2072f4c
Create Date: 2023-10-25 18:43:14.080786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453fe0350c8d'
down_revision = 'de3dc2072f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
