"""addtheracupp

Revision ID: 53b84dc1974c
Revises: 946d79da9400
Create Date: 2023-10-25 23:36:58.304885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b84dc1974c'
down_revision = '946d79da9400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smartgogglesProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smartgogglesProducts', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
