"""addtherafcke

Revision ID: 72e2a7d24b9b
Revises: b4629a74cb75
Create Date: 2023-10-25 22:23:19.138131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e2a7d24b9b'
down_revision = 'b4629a74cb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waveseriesProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('compatible', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('therafaceProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('theragunProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theragunProducts', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('therafaceProducts', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    op.drop_table('waveseriesProducts')
    # ### end Alembic commands ###
