"""addrecoveryair

Revision ID: 770b13f1bb37
Revises: 72e2a7d24b9b
Create Date: 2023-10-25 23:03:56.120397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770b13f1bb37'
down_revision = '72e2a7d24b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recoveryairProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('compatible', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recoveryairProducts')
    # ### end Alembic commands ###
