"""addrecoverytherm

Revision ID: 946d79da9400
Revises: 0291a9ea5a24
Create Date: 2023-10-25 23:16:39.601451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946d79da9400'
down_revision = '0291a9ea5a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recoverythermProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('compatible', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smartgogglesProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('compatible', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theracupProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('compatible', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theracupProducts')
    op.drop_table('smartgogglesProducts')
    op.drop_table('recoverythermProducts')
    # ### end Alembic commands ###
