"""all

Revision ID: e5b3a5fbc53a
Revises: 50a2127dc5c2
Create Date: 2023-10-27 23:38:21.652926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b3a5fbc53a'
down_revision = '50a2127dc5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powerdotProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('recoverythermProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('smartgogglesProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('description_url')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('theracupProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('therafaceProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('theragunProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('href', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('waveseriesProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waveseriesProducts', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    with op.batch_alter_table('theragunProducts', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('href')

    with op.batch_alter_table('therafaceProducts', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    with op.batch_alter_table('theracupProducts', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    with op.batch_alter_table('smartgogglesProducts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('description_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    with op.batch_alter_table('recoverythermProducts', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    with op.batch_alter_table('powerdotProducts', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
