"""empty message

Revision ID: 1f1ac655cc96
Revises: d43738348a79
Create Date: 2023-11-08 13:54:03.398920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1ac655cc96'
down_revision = 'd43738348a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinicsupplies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('electrodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('electrotherapy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('hot and cold', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('lightforceTherapy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('mobility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('portableElectrotherapy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('shockwave & RPW', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    with op.batch_alter_table('vitalstimTherapy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatible', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vitalstimTherapy', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('shockwave & RPW', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('portableElectrotherapy', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('mobility', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('lightforceTherapy', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('hot and cold', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('electrotherapy', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('electrodes', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    with op.batch_alter_table('clinicsupplies', schema=None) as batch_op:
        batch_op.drop_column('compatible')

    # ### end Alembic commands ###
